collections:
  questions:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "questions"
    values:
      layout: "question"
      is_question: true
  - scope:
      path: ""
    values:
      layout: "intro"

baseurl: "/teaching-dd14/es02/group07"
